tracker:
  input_video: "fixtures/videos/input/pets1s.mp4"
  output_video: "fixtures/videos/output/out.mp4"
  tracklet_detections: "fixtures/tmp/tracklet-detections.csv"
  frames_in_segment: 1
  detection_per_frames: 1
detectors:
  felzenszwalb:
    sth: 0